import { CHANGE_USER } from '../types'

const init = {
  profile: {
    idCard: '1840100464891',
    jcNumber: '',
    expireDateFlag: '',
    isNoDocExpDate: false,
    docExpDate: '',
    gender: '',
    genderCode: 'M',
    titleTH: '',
    firstNameTH: '',
    lastNameTH: '',
    firstNameEN: '',
    lastNameEN: '',
    birthDay: '-/-/2532',
    yearOfBirth: '',
    monthOfBirth: '',
    dayOfBirth: '',
    martialStatus: '',
    martialStatusCode: 'U',
    nationality: 'ไทย',
    nationalityCode: 'TH',
  },
  addressDoc: {
    country: '',
    countryCode: '',
    addressNoTH: '',
    moo: '',
    addressVillageTH: '',
    floorNo: '',
    trokSoiYaek: '',
    thanon: '',
    districtNameTH: '',
    districtCode: '',
    subDistrict: '',
    subDistrictCode: '',
    provinceNameTH: '',
    provinceCode: '',
    zipCode: '',
  },
  addressHome: {
    country: '',
    countryCode: 'TH',
    addressNoTH: '',
    moo: '',
    addressVillageTH: '',
    floorNo: '',
    trokSoiYaek: '',
    thanon: '',
    districtNameTH: '',
    districtCode: '',
    subDistrict: '',
    subDistrictCode: '',
    provinceNameTH: '',
    provinceCode: '',
    zipCode: '',
  },
  addressCurr: {
    country: '',
    countryCode: 'TH',
    addressNoTH: '',
    moo: '',
    addressVillageTH: '',
    floorNo: '',
    trokSoiYaek: '',
    thanon: '',
    districtNameTH: '',
    districtCode: '',
    subDistrict: '',
    subDistrictCode: '',
    provinceNameTH: '',
    provinceCode: '',
    zipCode: '',
  },
  addressWork: {
    countryCode: 'TH',
    companyName: '',
    addressNoTH: '',
    addressVillageTH: '',
    floorNo: '',
    moo: '',
    trokSoiYaek: '',
    thanon: '',
    districtNameTH: '',
    districtCode: '',
    subDistrict: '',
    subDistrictCode: '',
    provinceNameTH: '',
    provinceCode: '',
    zipCode: '',
  },
  contact: {
    workPhone: '',
    homePhone: '',
    mobilePhone: "0830015610",
    email: "b@b.com"
  },
  career: {
    busType: '',
    isicCode: '',
    occupation: '',
    occupationCode: '',
    incomeRange: '',
    incomeRangeCode: '',
    countrySourceOfIncome: '',
  },
  spouse: {
    nationFlag: '',
    nationalityCode: 'M',
    IDCardNo: '1111',
    marryCountry: 'bbbb',
    marryPassport: 'cccc',
    expireFlag: '',
    isIDCardExpDate: false,
    cardExpiredDate: 'bbb',
    marryExpireDate: 'eee',
    title: 'rrr',
    fistName: 'ttt',
    lastName: 'yyy',
    pepFlag: false,
  },
  sourceOfFund: {
    investmentSource: '',
    investmentSourceOther: '',
    investmentSourceCountry: '',
    investmentPurpose: '',
    dividendWithHoldingTax: false,
  }
}

export default (state = init, action) => {
  switch (action.type) {
    case CHANGE_USER:
      return { ...state, [action.key]: action.value }
    default:
      return state
  }
}