# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KbankOnboarding' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KbankOnboarding
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTLinkingIOS',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'Picker', :path => '../node_modules/react-native-picker'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'KbankOnboarding-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KbankOnboardingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
