export default [
  { routeName: 'passcode' },
  { routeName: 'condi' },
  { routeName: 'checkpoint' },
  { routeName: 'statusBank' },
  { routeName: 'waiting' },
  { routeName: 'lockUser' },
  { routeName: 'confirmAccount' },
  { routeName: 'statusApprove' },
  { routeName: 'softReject' },
  { routeName: 'portSuggestion' },
  { routeName: 'skip' },
  { routeName: 'idpStatusScreen' },
  { routeName: 'approving' },
  { routeName: 'autoApprove' },
  { routeName: 'waitingAutoApprove' },
]